# Generated by Django 4.2.6 on 2023-10-19 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparkmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-z\\d]{2,20}$', 'not valid')]),
        ),
    ]
