# Generated by Django 4.2.6 on 2023-10-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('autoparks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparkmodel',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.usermodel'),
            preserve_default=False,
        ),
    ]
