# Generated by Django 4.2.6 on 2023-10-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='vin',
            field=models.CharField(max_length=20),
        ),
    ]
