# Generated by Django 4.2.6 on 2023-10-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests', '0002_alter_partrequestmodel_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrequestmodel',
            name='car_brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='partrequestmodel',
            name='part_name',
            field=models.CharField(max_length=30),
        ),
    ]
