# Generated by Django 4.2.6 on 2023-10-19 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_autopark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-z\\d]{2,30}$', 'not valid')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
