# Generated by Django 4.2.6 on 2023-10-24 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_brand_alter_carmodel_engine_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{2,30}$', 'not valid')]),
        ),
    ]
