# Generated by Django 4.2.6 on 2023-10-25 12:01

import core.services.upload_avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar.upload_avatar_for_cars),
        ),
    ]
