# Generated by Django 4.2.6 on 2023-10-25 12:01

import core.services.upload_avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel_avatar_alter_profilemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.upload_avatar.upload_avatar_for_user),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
