# Generated by Django 4.2.6 on 2023-10-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
