# Generated by Django 4.2.6 on 2023-10-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usermodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.profilemodel'),
        ),
    ]
